In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
allsentence=["This pasta is very tasty and affordable",
             "This pasta is not very tasty and is affordable",
             "This pasta is very very delicious"]

In [ ]:
CountVectorizer=CountVectorizer()

In [ ]:
x=CountVectorizer.fit_transform(allsentence)

In [ ]:
result = x.toarray()

print(result)

[[1 1 0 1 0 1 1 1 1]
 [1 1 0 2 1 1 1 1 1]
 [0 0 1 1 0 1 0 1 2]]

In [ ]:
text = ['Hello my name is james',
'james this is my python notebook',
'james trying to create a big dataset',
'james of words to try differnt',
'features of count vectorizer']

In [ ]:
import pandas as pd
CountVectorizer=CountVectorizer()
x=CountVectorizer.fit_transform(text)
result = x.toarray()
df=pd.DataFrame(data=result,columns=CountVectorizer.get_feature_names())
df

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

   big  count  create  dataset  differnt  ...  to  try  trying  vectorizer  words
0    0      0       0        0         0  ...   0    0       0           0      0
1    0      0       0        0         0  ...   0    0       0           0      0
2    1      0       1        1         0  ...   1    0       1           0      0
3    0      0       0        0         1  ...   1    1       0           0      1
4    0      1       0        0         0  ...   0    0       0           1      0

[5 rows x 20 columns]

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
text=["hello my name is dhanya","Hello my name is dhanya"]
CountVectorizer=CountVectorizer(lowercase=False)
x=CountVectorizer.fit_transform(text)
result = x.toarray()
df=pd.DataFrame(data=result,columns=CountVectorizer.get_feature_names())
df

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

   Hello  dhanya  hello  is  my  name
0      0       1      1   1   1     1
1      1       1      0   1   1     1

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
text=["hello my name is dhanya","Hello my name is dhanya"]
CountVectorizer=CountVectorizer(stop_words=['is','my']#'english')
x=CountVectorizer.fit_transform(text)
result = x.toarray()
df=pd.DataFrame(data=result,columns=CountVectorizer.get_feature_names())
df

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

   dhanya  hello  name
0       1      1     1
1       1      1     1

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
text = ['This is the first document.','This document is the second document.','And this is the third one.', 'Is this the first document?',]
CountVectorizer=CountVectorizer(max_features=3)
x=CountVectorizer.fit_transform(text)
result = x.toarray()
df=pd.DataFrame(data=result,columns=CountVectorizer.get_feature_names())
df

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

   document  is  the
0         1   1    1
1         2   1    1
2         0   1    1
3         1   1    1

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
text = ['This is the first document. Is this the first document?' ]
CountVectorizer=CountVectorizer(binary=True)
x=CountVectorizer.fit_transform(text)
result = x.toarray()
df=pd.DataFrame(data=result,columns=CountVectorizer.get_feature_names())
df

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

   document  first  is  the  this
0         1      1   1    1     1